name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Copy env file
        run: cp /home/ins/.env .env

      - name: Build and deploy
        run: docker compose up --build -d
